/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.NumeroComplexo;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class TelaNumeroComplexo extends javax.swing.JFrame {

    NumeroComplexo x = null;
    NumeroComplexo y = null;
    /**
     * Creates new form TelaNumeroComplexo
     */
    public TelaNumeroComplexo() {
        initComponents();

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSoma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplica = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonIgualdade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldN1parteReal = new javax.swing.JTextField();
        jTextFieldN2parteReal = new javax.swing.JTextField();
        jTextFieldN1parteImaginaria = new javax.swing.JTextField();
        jTextFieldN2parteImaginaria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Numero Complexo");

        jButtonSoma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        jButtonSubtracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonMultiplica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonMultiplica.setText("*");
        jButtonMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicaActionPerformed(evt);
            }
        });

        jButtonDivisao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonIgualdade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonIgualdade.setText("==");
        jButtonIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualdadeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("N1");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("N2");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("PR");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("PI");

        jLabel5.setText("i");

        jLabel6.setText("i");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldN2parteReal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldN1parteReal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jButtonSoma)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSubtracao))))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultiplica)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDivisao)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIgualdade))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldN2parteImaginaria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jTextFieldN1parteImaginaria, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldN1parteReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldN1parteImaginaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldN2parteReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldN2parteImaginaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSoma)
                    .addComponent(jButtonSubtracao)
                    .addComponent(jButtonMultiplica)
                    .addComponent(jButtonDivisao)
                    .addComponent(jButtonIgualdade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        try {
             x = new NumeroComplexo();
            x.set(Integer.parseInt(jTextFieldN1parteReal.getText()),
                    (Integer.parseInt(jTextFieldN1parteImaginaria.getText())));

             y = new NumeroComplexo(Integer.parseInt(jTextFieldN2parteReal.getText()),
                    Integer.parseInt(jTextFieldN2parteImaginaria.getText()));
            
            NumeroComplexo w = new NumeroComplexo(x);
            
            NumeroComplexo auxSoma = x.adiciona(y);           

            String saida = "Valor de x = " + x.get() + "\n";
            saida += "Valor de y = " + y.get() + "\n";
            saida += "Valor de x + y = " + auxSoma.get() + "\n";
            jTextAreaSaida.setText(saida);

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        


    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        // TODO add your handling code here:
        try {
             x = new NumeroComplexo();

            x.set(Integer.parseInt(jTextFieldN1parteReal.getText()),
                    Integer.parseInt(jTextFieldN1parteImaginaria.getText()));

             y = new NumeroComplexo(Integer.parseInt(jTextFieldN2parteReal.getText()),
                    Integer.parseInt(jTextFieldN2parteImaginaria.getText()));

            NumeroComplexo resultado = x.dividir(y);
            String saida = "Valor de x = " + x.get() + "\n";
            saida += "Valor de y = " + y.get() + "\n";
            saida += "Valor de x / y = " + resultado.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        

    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        // TODO add your handling code here:
        try {
             x = new NumeroComplexo();

            x.set(Integer.parseInt(jTextFieldN1parteReal.getText()),
                    Integer.parseInt(jTextFieldN1parteImaginaria.getText()));

             y = new NumeroComplexo(Integer.parseInt(jTextFieldN2parteReal.getText()),
                    Integer.parseInt(jTextFieldN2parteImaginaria.getText()));

            NumeroComplexo auxSubtracao = x.subtrai(y);
            String saida = "Valor de x = " + x.get() + "\n";
            saida += "Valor de y = " + y.get() + "\n";
            saida += "Valor de y - x = " + auxSubtracao.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicaActionPerformed
        // TODO add your handling code here:
        try {
             x = new NumeroComplexo();

            x.set(Integer.parseInt(jTextFieldN1parteReal.getText()),
                    Integer.parseInt(jTextFieldN1parteImaginaria.getText()));

             y = new NumeroComplexo(Integer.parseInt(jTextFieldN2parteReal.getText()),
                    Integer.parseInt(jTextFieldN2parteImaginaria.getText()));

            NumeroComplexo auxMultiplicar = x.multiplica(y);
            String saida = "Valor de x = " + x.get() + "\n";
            saida += "Valor de y = " + y.get() + "\n";
            saida += "Valor de x * y = " + auxMultiplicar.get() + "\n";
jTextAreaSaida.setText(saida);
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        

    }//GEN-LAST:event_jButtonMultiplicaActionPerformed

    private void jButtonIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualdadeActionPerformed
        // TODO add your handling code here:

        try {
             x = new NumeroComplexo();
            x.set(Integer.parseInt(jTextFieldN1parteReal.getText()),
                    (Integer.parseInt(jTextFieldN1parteImaginaria.getText())));

             y = new NumeroComplexo(Integer.parseInt(jTextFieldN2parteReal.getText()),
                    Integer.parseInt(jTextFieldN2parteImaginaria.getText()));

            String saida = "Valor de x = " + x.get() + "\n";
            saida += "Valor de y = " + y.get() + "\n";
            saida += "x é igual a y ? = " + x.eIgual(y) + "\n";
            jTextAreaSaida.setText(saida);

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

       
    }//GEN-LAST:event_jButtonIgualdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroComplexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroComplexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroComplexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroComplexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNumeroComplexo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgualdade;
    private javax.swing.JButton jButtonMultiplica;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldN1parteImaginaria;
    private javax.swing.JTextField jTextFieldN1parteReal;
    private javax.swing.JTextField jTextFieldN2parteImaginaria;
    private javax.swing.JTextField jTextFieldN2parteReal;
    // End of variables declaration//GEN-END:variables
}
